"""
CandlePatternMemory – OTC-specific pattern recognition.

For OTC binary options the price feed is generated by the broker with no
connection to real markets.  However, the pseudo-random generator can carry
biases: patterns that resolve to UP/DOWN more often than chance.

How it works:
  1. Quantise recent candles into a direction fingerprint (U/u/N/d/D)
  2. Track fingerprint → {wins, losses} across multiple window sizes (3,5,8)
  3. On lookup, return the historical win-rate for the current pattern
  4. After ~thousands of trades this map becomes a real edge for OTC

Persisted to knowledge/pattern_memory.json so learning survives restarts.
"""
import json
import logging
import os
import time
from typing import Dict, List, Optional, Tuple

import pandas as pd

logger = logging.getLogger(__name__)


class CandlePatternMemory:
    """
    Dictionary: fingerprint → {wins, losses, total, last_seen}.
    Multi-resolution: maintains separate windows of 3, 5, and 8 candles.
    """

    WINDOWS         = (3, 5, 8)   # candle window sizes to track
    MIN_SAMPLES     = 4            # minimum trades before trusting win-rate
    SAVE_EVERY      = 20           # flush to disk every N records

    def __init__(self, base_dir: str = "./knowledge"):
        self._path  = os.path.join(base_dir, "pattern_memory.json")
        self._db: Dict[str, dict] = {}
        self._pending = 0
        self._load()

    # ── Public ────────────────────────────────────────────────────────────────

    def record(self, candles: pd.DataFrame, outcome: float) -> None:
        """Record (last N candles fingerprint → outcome). Call after every trade."""
        if candles is None or len(candles) < max(self.WINDOWS):
            return
        ts = time.time()
        for w in self.WINDOWS:
            key = self._fingerprint(candles, w)
            if key not in self._db:
                self._db[key] = {"wins": 0, "losses": 0, "total": 0,
                                  "last_seen": ts, "w": w}
            e = self._db[key]
            e["total"]     += 1
            e["last_seen"]  = ts
            if outcome > 0:
                e["wins"] += 1
            elif outcome < 0:
                e["losses"] += 1

        self._pending += 1
        if self._pending >= self.SAVE_EVERY:
            self._save()
            self._pending = 0

    def lookup(self, candles: pd.DataFrame) -> Optional[Tuple[float, float, int]]:
        """
        Returns (win_rate, confidence, total_samples) or None if too few data.
        Averages results across all window sizes that have >= MIN_SAMPLES.
        win_rate > 0.55 → lean BUY; < 0.45 → lean SELL; 0.45-0.55 → neutral.
        """
        if candles is None or len(candles) < max(self.WINDOWS):
            return None
        results = []
        for w in self.WINDOWS:
            key = self._fingerprint(candles, w)
            e   = self._db.get(key)
            if e and e["total"] >= self.MIN_SAMPLES:
                wr   = e["wins"] / e["total"]
                conf = min(0.85, 0.50 + e["total"] * 0.015)
                results.append((wr, conf, e["total"]))
        if not results:
            return None
        total_n = sum(r[2] for r in results)
        avg_wr  = sum(r[0] * r[2] for r in results) / total_n
        avg_cf  = sum(r[1] * r[2] for r in results) / total_n
        return avg_wr, avg_cf, total_n

    def stats(self) -> dict:
        total   = len(self._db)
        trusted = sum(1 for e in self._db.values() if e["total"] >= self.MIN_SAMPLES)
        wins    = sum(e["wins"]   for e in self._db.values())
        losses  = sum(e["losses"] for e in self._db.values())
        return {"total_patterns": total, "trusted": trusted,
                "wins": wins, "losses": losses}

    def flush(self) -> None:
        self._save()
        self._pending = 0

    # ── Fingerprinting ────────────────────────────────────────────────────────

    @staticmethod
    def _fingerprint(candles: pd.DataFrame, window: int) -> str:
        """
        Reduce the last `window` candles to a compact token string.
        Token per candle: U (strong up) / u (mild up) / N (doji) / d (mild down) / D (strong down)
        """
        df = candles.tail(window)
        tokens = []
        for _, row in df.iterrows():
            o = float(row["open"])
            h = float(row["high"])
            l = float(row["low"])
            c = float(row["close"])
            rng   = (h - l) or 1e-9
            body  = c - o
            ratio = abs(body) / rng
            if ratio < 0.05:
                tok = "N"
            elif body > 0:
                tok = "U" if ratio > 0.20 else "u"
            else:
                tok = "D" if ratio > 0.20 else "d"
            tokens.append(tok)
        return f"w{window}:{''.join(tokens)}"

    # ── Persistence ───────────────────────────────────────────────────────────

    def _load(self) -> None:
        if os.path.exists(self._path):
            try:
                with open(self._path, "r") as f:
                    self._db = json.load(f)
                st = self.stats()
                logger.info("PatternMemory: %d patterns (%d trusted)",
                            st["total_patterns"], st["trusted"])
            except Exception as exc:
                logger.warning("PatternMemory load failed (%s) — starting fresh", exc)
                self._db = {}

    def _save(self) -> None:
        try:
            os.makedirs(os.path.dirname(self._path) or ".", exist_ok=True)
            tmp = self._path + ".tmp"
            with open(tmp, "w") as f:
                json.dump(self._db, f, separators=(",", ":"))
            os.replace(tmp, self._path)
        except Exception as exc:
            logger.warning("PatternMemory save failed: %s", exc)
