"""
CandlePatternMemory v2 – OTC-specific pattern recognition.

For OTC binary options the price feed is generated by the broker with no
connection to real markets.  However, the pseudo-random generator carries
biases: patterns that resolve UP/DOWN more often than chance.

v2 improvements over v1:
  ▸ Volatility context token (V_H/V_M/V_L) appended to fingerprint
    — same candle sequence in high-vol vs low-vol contexts carries different
      predictive value.
  ▸ Hourly bias tracking: OTC generators may exhibit time-of-day patterns.
    win rates per hour are tracked and blended with the fingerprint win-rate.
  ▸ Laplace smoothing: (wins+1)/(total+2) prevents extreme estimates from
    small samples.
  ▸ Staleness penalty: patterns not seen in 7 days get 70 % confidence weight
    (generator may drift over time).
  ▸ Multi-window weighted average: longer windows carry more weight when
    trusted (more samples).

Persisted to knowledge/pattern_memory.json so learning survives restarts.
"""
import json
import logging
import math
import os
import time
from typing import Dict, List, Optional, Tuple

import pandas as pd

logger = logging.getLogger(__name__)

_STALE_SECS  = 7 * 86_400   # 7 days
_WINDOW_W    = {3: 1.0, 5: 1.5, 8: 2.0}   # longer windows trusted more


class CandlePatternMemory:
    """
    Dictionary: fingerprint → {wins, losses, total, last_seen}.
    Multi-resolution: maintains separate windows of 3, 5, and 8 candles.
    Fingerprint format: "V_H:w5:UuNdD"
      — volatility prefix (V_H/V_M/V_L) + window size + directional tokens.
    """

    WINDOWS         = (3, 5, 8)
    MIN_SAMPLES     = 4           # minimum trades before trusting win-rate
    SAVE_EVERY      = 20          # flush to disk every N records

    def __init__(self, base_dir: str = "./knowledge"):
        self._path        = os.path.join(base_dir, "pattern_memory.json")
        self._db:         Dict[str, dict] = {}   # fingerprint → entry
        self._hourly:     Dict[int, dict] = {    # 0-23 → {wins, total}
            h: {"wins": 0, "total": 0} for h in range(24)
        }
        self._pending = 0
        self._load()

    # ── Public API ────────────────────────────────────────────────────────────

    def record(self, candles: pd.DataFrame, outcome: float) -> None:
        """Record (last N candles fingerprint → outcome). Call after every trade."""
        if candles is None or len(candles) < max(self.WINDOWS):
            return
        ts   = time.time()
        hour = int(time.localtime(ts).tm_hour)
        won  = outcome > 0

        for w in self.WINDOWS:
            key = self._fingerprint(candles, w)
            if key not in self._db:
                self._db[key] = {"wins": 0, "losses": 0, "total": 0,
                                  "last_seen": ts, "w": w}
            e = self._db[key]
            e["total"]    += 1
            e["last_seen"] = ts
            if won:
                e["wins"]   += 1
            elif outcome < 0:
                e["losses"] += 1

        # Hourly bias tracking
        h = self._hourly[hour]
        h["total"] += 1
        if won:
            h["wins"] += 1

        self._pending += 1
        if self._pending >= self.SAVE_EVERY:
            self._save()
            self._pending = 0

    def lookup(self, candles: pd.DataFrame) -> Optional[Tuple[float, float, int]]:
        """
        Returns (win_rate, confidence, total_samples) or None.

        win_rate uses Laplace smoothing: (wins+1)/(total+2).
        confidence blends pattern frequency with hourly bias.
        Staleness penalty applied if pattern not seen for 7+ days.
        """
        if candles is None or len(candles) < max(self.WINDOWS):
            return None

        now  = time.time()
        hour = int(time.localtime(now).tm_hour)

        results: List[Tuple[float, float, int, float]] = []  # wr, conf, n, weight
        for w in self.WINDOWS:
            key = self._fingerprint(candles, w)
            e   = self._db.get(key)
            if e is None or e["total"] < self.MIN_SAMPLES:
                continue

            # Laplace-smoothed win rate
            wr   = (e["wins"] + 1) / (e["total"] + 2)

            # Confidence: grows with samples, capped at 0.85
            conf = min(0.85, 0.50 + e["total"] * 0.012)

            # Staleness penalty
            age  = now - e.get("last_seen", now)
            if age > _STALE_SECS:
                conf *= 0.70

            results.append((wr, conf, e["total"], _WINDOW_W[w]))

        if not results:
            return None

        # Weighted average (longer windows get more weight when trusted)
        total_weight = sum(r[3] * r[2] for r in results)
        if total_weight == 0:
            return None
        avg_wr = sum(r[0] * r[3] * r[2] for r in results) / total_weight
        avg_cf = sum(r[1] * r[3] * r[2] for r in results) / total_weight
        total_n = sum(r[2] for r in results)

        # Blend with hourly bias (30 % weight if there's enough hourly data)
        h_data = self._hourly.get(hour, {"wins": 0, "total": 0})
        if h_data["total"] >= 10:
            h_wr  = (h_data["wins"] + 1) / (h_data["total"] + 2)
            avg_wr = avg_wr * 0.75 + h_wr * 0.25

        return avg_wr, avg_cf, total_n

    def stats(self) -> dict:
        total   = len(self._db)
        trusted = sum(1 for e in self._db.values() if e["total"] >= self.MIN_SAMPLES)
        wins    = sum(e["wins"]   for e in self._db.values())
        losses  = sum(e["losses"] for e in self._db.values())
        hourly_wr = {
            h: round((d["wins"] + 1) / (d["total"] + 2), 3)
            for h, d in self._hourly.items()
            if d["total"] >= 5
        }
        return {
            "total_patterns": total,
            "trusted":        trusted,
            "wins":           wins,
            "losses":         losses,
            "hourly_bias":    hourly_wr,
        }

    def flush(self) -> None:
        self._save()
        self._pending = 0

    # ── Fingerprinting ────────────────────────────────────────────────────────

    @staticmethod
    def _vol_token(candles: pd.DataFrame, window: int) -> str:
        """Compute volatility category V_H / V_M / V_L for a candle window."""
        df = candles.tail(window)
        ratios = []
        for _, row in df.iterrows():
            h = float(row["high"])
            l = float(row["low"])
            rng = (h - l) or 1e-9
            o   = float(row["open"])
            c   = float(row["close"])
            ratios.append(abs(c - o) / rng)
        if not ratios:
            return "V_M"
        mean_r = sum(ratios) / len(ratios)
        if mean_r > 0.40:
            return "V_H"
        if mean_r < 0.12:
            return "V_L"
        return "V_M"

    @classmethod
    def _fingerprint(cls, candles: pd.DataFrame, window: int) -> str:
        """
        Reduce the last `window` candles to a compact token string.
        Format: "V_M:w5:UuNdD"
        Volatility prefix: V_H (high body ratio) / V_M (medium) / V_L (low/doji-heavy)
        Direction tokens: U (strong up) / u (mild up) / N (doji) / d (mild down) / D (strong down)
        """
        vol = cls._vol_token(candles, window)
        df  = candles.tail(window)
        tokens = []
        for _, row in df.iterrows():
            o   = float(row["open"])
            h   = float(row["high"])
            l   = float(row["low"])
            c   = float(row["close"])
            rng = (h - l) or 1e-9
            body = c - o
            ratio = abs(body) / rng
            if ratio < 0.05:
                tok = "N"
            elif body > 0:
                tok = "U" if ratio > 0.20 else "u"
            else:
                tok = "D" if ratio > 0.20 else "d"
            tokens.append(tok)
        return f"{vol}:w{window}:{''.join(tokens)}"

    # ── Persistence ───────────────────────────────────────────────────────────

    def _load(self) -> None:
        if not os.path.exists(self._path):
            return
        try:
            with open(self._path, "r") as f:
                data = json.load(f)
            # Support both old format (bare dict) and new format (with hourly key)
            if isinstance(data, dict) and "_hourly" in data:
                loaded_hourly = data.get("_hourly", {})
                self._hourly = {
                    int(k): v for k, v in loaded_hourly.items()
                }
                # Fill missing hours
                for h in range(24):
                    if h not in self._hourly:
                        self._hourly[h] = {"wins": 0, "total": 0}
                self._db = data.get("_db", {})
            else:
                # Old format: data IS the fingerprint dict — migrate (drop old keys)
                self._db = {k: v for k, v in data.items()
                            if isinstance(v, dict) and "total" in v}
            st = self.stats()
            logger.info("PatternMemory v2: %d patterns (%d trusted)",
                        st["total_patterns"], st["trusted"])
        except Exception as exc:
            logger.warning("PatternMemory load failed (%s) — starting fresh", exc)
            self._db = {}

    def _save(self) -> None:
        try:
            os.makedirs(os.path.dirname(self._path) or ".", exist_ok=True)
            payload = {
                "_db":     self._db,
                "_hourly": {str(k): v for k, v in self._hourly.items()},
            }
            tmp = self._path + ".tmp"
            with open(tmp, "w") as f:
                json.dump(payload, f, separators=(",", ":"))
            os.replace(tmp, self._path)
        except Exception as exc:
            logger.warning("PatternMemory save failed: %s", exc)
